---
title: "Introduzione a R e Quarto"
format:
  html:
    code-fold: show
    code-tools: true
---

Ci sono tantissime risorse in rete che fornisco un'introduzione a R. Per le funzionalità di base, consiglio [An Introduction to R](https://intro2r.com). Per un'introduzione alle funzionalità di tidyverse, consiglio [Introduction to R with Tidyverse](https://introduction-r-tidyverse.netlify.app).

In questo laboratorio useremo Quarto che consente di creare dei notebook che contengono sia testo sia codice. Questo sito web è stato costruito usando Quarto. Una delle interessanti proprietà di Quarto è che permette di avere codice R e codice Python nello stesso notebook. Per un'introduzione, la risorsa migliore è il sito di [Quarto](https://quarto.org).

# File `qmd`

Questa pagina è un esempio dell'uso di un file `qmd` come documento sorgente. 

## Esecuzione di codice Python, con un grafico

```{python}
import numpy as np
x = np.random.normal(size=100)
import matplotlib.pyplot as plt
plt.hist(x)
plt.show()
np.mean(x)
```


## $\LaTeX$

$$
\theta = \int_0^\infty f(x,\theta)d\theta
$$


## Div stilizzato tramite HTML diretto

::: {.border}
Questo contenuto può essere stilizzato tramite la classe border.
:::

## Un avviso

::: {.callout-tip}
## Suggerimento con Titolo

Questo è un esempio di un avviso con un titolo.
:::

## Set di tab 

::: {.panel-tabset}
## R

Questo codice non viene eseguito.

```{.r}
fizz_buzz <- function(fbnums = 1:50) {
  output <- dplyr::case_when(
    fbnums %% 15 == 0 ~ "FizzBuzz",
    fbnums %% 3 == 0 ~ "Fizz",
    fbnums %% 5 == 0 ~ "Buzz",
    TRUE ~ as.character(fbnums)
  )
  print(output)
}

fizz_buzz(3)
```

## Python

Questo codice viene eseguito.

```{python}
def fizz_buzz(num):
  if num % 15 == 0:
    print("FizzBuzz")
  elif num % 5 == 0:
    print("Buzz")
  elif num % 3 == 0:
    print("Fizz")
  else:
    print(num)
    
fizz_buzz(3)
```

:::

